### ISSUE TITLE
Can this lib support RSA Encrypt&Decrypt

### ISSUE THREAD

**Issue by hustwcw** [bigsan/RSAESCryptor#1]
I just scaned the code, and found that there was only support for AES. In the readme file of this project, you declare that it can support RSA & AES.

**Comment by bigsan** [comment]
Due to the poor performance of asymmetric encrypt/decrypt algorithms such as RSA or DSA, we usually don't encrypt the whole data with them.

Instead we encrypt the "data" with a random generated symmetric key (here is AES), then encrypt that "key" with public key using asymmetric algorithm (see wrapSymmetricKey:keyRef: and SecKeyEncrypt in RSAESCryptor.m), finally put them together for delivery.

So this lib supports RSA+AES encrypt/decrypt, but not RSA and/or AES encrypt/decrypt.
